server:
  port: 8888

spring:
  rabbitmq:
    host: "rabbitmq"
    port: 5672
    username: "guest"
    password: "guest"

management:
  endpoints:
    web:
      exposure:
        include: "busrefresh"
