management:
  endpoints:
    web:
      exposure:
        include: "*"

spring:
  datasource:
    url: jdbc:h2:mem:store
    username: store
    password: store
  jpa:
    defer-datasource-initialization: true
    properties:
      hibernate:
        '[show_sql]': true
        '[format_sql]': true
  sql:
    init:
      mode: always
      platform: h2
