management:
  endpoints:
    web:
      exposure:
        include: "*"
    env:
      show-values: "always"
    configprops:
      show-values: "always"

spring:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://mysql.harsh.rathod.dev:3306/store
    username: store
    password: store1234
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: "update"
    properties:
      hibernate:
        '[show_sql]': true
        '[format_sql]': true
  sql:
    init:
      mode: always
      platform: mysql
