management:
  endpoints:
    web:
      exposure:
        include: "*"

spring:
  datasource:
    url: jdbc:h2:mem:emedicare
    username: emedicare
    password: emedicare
  jpa:
    defer-datasource-initialization: true
    properties:
      hibernate:
        '[show_sql]': true
        '[format_sql]': true
  sql:
    init:
      mode: always
      platform: h2
